### ISSUE TITLE
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/Tessellator

### ISSUE THREAD

**Issue by MrSliTraP2716Lua** [FalsePattern/FalseTweaks#234]
[crash-2025-10-24_09.37.40-client.txt](https://github.com/user-attachments/files/23114112/crash-2025-10-24_09.37.40-client.txt)

The reason is in versions 4.0.0+ and Foam Fix, because everything worked on 3.9.7, but I can't roll back because of the hard binding to the Lumi, RPLE, SwanSong mod complex. Yes, as you advised, I have already come to terms with OptiFine and switched to Beddium. Or should I use Bug Fix instead of Foam Fix?

**Comment by FalsePattern** [comment]
Yeah, BugTorch+CoreTweaks should fix the same issues that FoamFix fixes as far as i know

**Comment by MrSliTraP2716Lua** [comment]
In short, this is fixed by enabling the Tessellation option in the Foam Fix config. Why was it disabled? Because I suddenly started experiencing crashes when entering the normal world, and I didn't seem to change anything, but it might have happened due to improperly combining mods. I was testing another mod, and it complained most about Optifine, even though everything worked fine with the option enabled.
Then I'm closing this ticket, as the problem was most likely due to the incorrect order of my mods initially, especially OptiFine in the past. And I ask that SwanSong be made more stable, as shaders like Continium aren't selectable, and compatibility is also poor with the Thermal Dynamics mod. Caps don't render, and when placed, they cause multicolored artifacts like Neodymium and Shaders Core.
